---
# tasks file for powervs-bastion-as-router
- name: Enable IP masquerade in public firewalld zone
  ansible.posix.firewalld:
    masquerade: yes
    state: enabled
    permanent: yes
    zone: public

- name: Reload firewalld service
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Set dhcpd routers values to bastion ip
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhcpd.conf
    regex: "option routers"
    line: "    option routers                  {{ router_ipv4_address }};"
  vars:
    router_ipv4_address: "{{ lookup('vars', 'ansible_' + router_interface).ipv4.address }}"

- name: Set dhcpd interface mtu value
  ansible.builtin.lineinfile:
    path: /etc/dhcp/dhcpd.conf
    regex: "option interface-mtu"
    line: "    option interface-mtu            {{ private_network_mtu }};"
    insertafter: "option domain-search"

- name: Restart dhcpd service
  ansible.builtin.service:
    name: dhcpd
    state: restarted
